export const POST_MATCHINGREGISTRATION =
  "MATCHINGREGISTRATION/POST_MATCHINGREGISTRATION" as const;
export const POST_MATCHINGREGISTRATION_SUCCESS =
  "MATCHINGREGISTRATION/POST_MATCHINGREGISTRATION_SUCCESS" as const;
export const POST_MATCHINGREGISTRATION_FAILURE =
  "MATCHINGREGISTRATION/POST_MATCHINGREGISTRATION_FAILURE" as const;
export const SET_MATCH_OPTION =
  "MATCHINGREGISTRATION/SET_MATCH_OPTION" as const;
export const SET_NOTICE_MESSAGE =
  "MATCHINGREGISTRATION/SET_NOTICE_MESSAGE" as const;
export const SET_PAGE = "MATCHINGREGISTRATION/SET_PAGE" as const;
